repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/OneKeyHQ/google-style-precommit-hook
    rev: e7990326dd4a22631bffca2bcf8abba49582f23e
    hooks:
    -   id: google-style-java
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
      - id: clang-format
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        files: ^electrum_gui
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        files: ^electrum_gui
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 39ceae7491f4121902a5dccc22657a0675c95539
    hooks:
      - id: flake8
        files: ^electrum_gui
      - id: flake8
        alias: flake8-compat
        exclude: ^electrum_gui
        args: [--ignore, "F821", --select, "E9,F63,F7,F82"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        files: ^electrum_gui
        args: [--skip, "B107,B101,B106",]
